export const qrySiteSettings = groq`
*[_type == 'settings'][0]{
  siteOwner,
  title,
  logo{
    asset->{
      _id,
      url,
      metadata
    }
  },
  image{
    asset->{
      _id,
      url,
      metadata
    }
  },
  clrPrimary,
  clrSecondary,
  fontPrimary,
  fontSecondary,
  description,
  'email':primaryLocation->email,
  'address':primaryLocation->address,
  'addressExt':primaryLocation->addressExt,
  'city':primaryLocation->city,
  'postcode':primaryLocation->postcode,
  'country':primaryLocation->country,
  'state':primaryLocation->state,
  primaryLocation->{
    'lat':mapLocation.lat,
    'lng':mapLocation.lng,
    phoneNumbers[]{
      number,
    },
    socialConnections[]{
      _type,
      title,
      'url': url + username,
    }
  }
}
`;

export const qrySiteNavigation = groq`
{
  "mainNav":*[_type=="navigation" && _id == "mainNavigation"][0]{
    _id,
    name,
    navigationLinks[]{
      _key,
      name,
      linkType,
      externalLink{
        _type,
        newWindow,
        url
      },
      internalLink{
        _type,
        reference->{
          _id,
          'slug':slug.current,
          title,
        }
      },
      anchorLink{
        _type,
        anchor,
        page->{
          _id,
        title,
        'slug':slug.current
        }
      }
    }
  },
  "footerNav":*[_type=="navigation" && _id == "footerNavigation"][0]{
    _id,
    name,
    navigationLinks[]{
      _key,
      name,
      linkType,
      externalLink{
        _type,
        newWindow,
        url
      },
      internalLink{
        _type,
        reference->{
          _id,
          'slug':slug.current,
          title,
        }
      },
      anchorLink{
        _type,
        anchor,
        page->{
          _id,
        title,
        'slug':slug.current
        }
      }
    }
  },
  "otherNav":*[_type=="navigation" && _id != 'mainNavigation' && _id != 'footerNavigation'][0]{
    _id,
    name,
    navigationLinks[]{
      _key,
      name,
      linkType,
      externalLink{
        _type,
        newWindow,
        url
      },
      internalLink{
        _type,
        reference->{
          _id,
          'slug':slug.current,
          title,
        }
      },
      anchorLink{
        _type,
        anchor,
        page->{
          _id,
        title,
        'slug':slug.current
        }
      }
    }
  }
}
`;

export const qryPage = groq`
  *[_type == 'page' && slug.current==$slug && isActive][0]{
    title,
    isActive,
    'slug':slug.current,
    headerImage{
      asset->{
        _id,
        url,
        metadata
      }
    },
    body,
    _id,
    seo{
      title,
      description,
    },
    sections[]->{
      _type,
      _id,
      title,
      layout,
    }
  }
`;

export const qryHomePage = groq`
  *[_type == 'homepage'][0]{
    title,
    'image':{
      asset->{
        url,
        _id,
        metadata
      }
    },
    body,
    _id,
    seo{
      description,
      image{
        asset->{
          url,
          _id,
          metadata
        }
      }
    },
    sections[]->{
      _type,
      _id,
      title,
      layout
    }
  }
`;

export const qryContactPage = groq`
  *[_type == 'contactpage'][0]{
    title,
    image{
      asset->{
        url,
        _id,
        metadata
      }
    },
    content,
    _id,
    seo{
      description,
      image{
        asset->{
          url,
          _id,
          metadata
        }
      }
    },
    sections[]->{
      _type,
      _id,
      title,
      layout
    }
  }
`;
